# Generated by Django 5.0 on 2024-05-31 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycontact',
            name='user',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mycontact',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
