# Generated by Django 5.0 on 2024-05-31 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_mycontact_user_alter_mycontact_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycontact',
            old_name='name',
            new_name='contact',
        ),
    ]
