# Generated by Django 5.0 on 2024-05-31 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_rename_name_mycontact_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycontact',
            name='user_phone_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mycontact',
            name='phone_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
