# Generated by Django 5.0 on 2024-05-31 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_mycontact_user_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Profile Image')),
                ('username', models.CharField(max_length=255)),
                ('bio', models.TextField()),
            ],
        ),
    ]
