# Generated by Django 5.0 on 2024-06-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='first_name',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='blank.png', upload_to='Profile Image'),
        ),
    ]
