# Generated by Django 5.0 on 2024-06-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_profile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='Status')),
                ('text', models.TextField()),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
