# Generated by Django 5.0 on 2024-06-01 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='time',
            field=models.TimeField(),
        ),
    ]
