# Generated by Django 5.0 on 2024-06-01 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_status_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycontact',
            name='image',
            field=models.ImageField(default='blank.png', upload_to='Profile Image'),
        ),
    ]
