# Generated by Django 5.0 on 2024-06-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_mycontact_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
