# Generated by Django 5.0 on 2024-06-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_alter_status_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
