# Generated by Django 5.0 on 2024-06-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_alter_status_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='time',
            field=models.TimeField(),
        ),
    ]
