# Generated by Django 5.0 on 2024-06-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_alter_status_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='file',
        ),
        migrations.AddField(
            model_name='status',
            name='image',
            field=models.FileField(null=True, upload_to='Status'),
        ),
        migrations.AddField(
            model_name='status',
            name='video',
            field=models.FileField(null=True, upload_to='Status'),
        ),
    ]
