# Generated by Django 5.0 on 2024-07-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_alter_profile_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=255, null=True)),
                ('receiver', models.CharField(max_length=255, null=True)),
                ('receiverId', models.CharField(max_length=255, null=True)),
                ('senderId', models.CharField(max_length=255, null=True)),
                ('message', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
