# Generated by Django 5.0 on 2024-07-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycontact',
            name='user_image',
            field=models.ImageField(default='blank.png', upload_to='Profile Image'),
        ),
    ]
