# Generated by Django 5.0 on 2024-07-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0024_mycontact_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycontact',
            name='bio',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
