# Generated by Django 5.0 on 2024-07-25 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_mycontact_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycontact',
            name='last_message',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
