# Generated by Django 5.0 on 2024-07-25 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0026_mycontact_last_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycontact',
            name='last_message',
            field=models.CharField(default='No messages', max_length=255),
        ),
    ]
