# Generated by Django 5.0 on 2024-08-06 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0027_alter_mycontact_last_message'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_admin', models.CharField(max_length=255, null=True)),
                ('group_pic', models.ImageField(upload_to='Group image')),
                ('group_members', models.CharField(max_length=255, null=True)),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
    ]
