# Generated by Django 5.0 on 2024-08-07 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_communities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communities',
            name='group_members',
            field=models.IntegerField(null=True),
        ),
    ]
