# Generated by Django 5.0 on 2024-08-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0029_alter_communities_group_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communities',
            name='group_pic',
            field=models.ImageField(default='blank.png', upload_to='Group image'),
        ),
    ]
