# Generated by Django 5.0 on 2024-08-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0030_alter_communities_group_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50000000, null=True)),
                ('comment', models.CharField(max_length=50000000, null=True)),
                ('userId', models.CharField(max_length=50, null=True)),
                ('profileimage', models.ImageField(default='blank.png', upload_to='')),
                ('group_name', models.CharField(max_length=50000000, null=True)),
            ],
        ),
    ]
