# Generated by Django 5.0 on 2024-08-08 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0031_group_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group_comment',
            old_name='name',
            new_name='sender',
        ),
    ]
