# Generated by Django 5.0 on 2024-08-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0032_rename_name_group_comment_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
