# Generated by Django 5.0 on 2024-08-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0035_status_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
