# Generated by Django 5.0 on 2024-08-28 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0036_status_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstatus',
            name='status',
        ),
    ]
