# Generated by Django 5.0 on 2024-08-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0039_alter_userstatus_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='image',
            field=models.ImageField(null=True, upload_to='Status'),
        ),
        migrations.AddField(
            model_name='userstatus',
            name='video',
            field=models.FileField(null=True, upload_to='Status'),
        ),
    ]
