# Generated by Django 5.0 on 2024-08-28 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0040_userstatus_image_userstatus_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstatus',
            old_name='video',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='userstatus',
            name='user',
        ),
    ]
