# Generated by Django 5.0 on 2024-08-28 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0041_rename_video_userstatus_file_remove_userstatus_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstatus',
            name='file',
        ),
        migrations.AddField(
            model_name='userstatus',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userstatus',
            name='video',
            field=models.FileField(null=True, upload_to='Status'),
        ),
    ]
