# Generated by Django 5.0 on 2024-08-29 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0042_remove_userstatus_file_userstatus_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstatus',
            old_name='video',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='userstatus',
            name='image',
        ),
    ]
