# Generated by Django 5.0 on 2024-08-28 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0043_rename_video_userstatus_file_remove_userstatus_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstatus',
            old_name='file',
            new_name='video',
        ),
        migrations.AddField(
            model_name='userstatus',
            name='image',
            field=models.ImageField(null=True, upload_to='Status'),
        ),
    ]
