# Generated by Django 5.0 on 2024-09-10 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0044_rename_file_userstatus_video_userstatus_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='status',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
