# Generated by Django 5.0 on 2024-09-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0045_userstatus_time_alter_status_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.FileField(null=True, upload_to='Chat'),
        ),
        migrations.AddField(
            model_name='message',
            name='video',
            field=models.FileField(null=True, upload_to='Chat'),
        ),
    ]
