# Generated by Django 5.0 on 2024-10-02 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0046_message_image_message_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_activity',
        ),
    ]
