# Generated by Django 5.0 on 2024-10-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0047_remove_profile_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycontact',
            name='last_message_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
