# Generated by Django 5.0 on 2024-10-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0048_mycontact_last_message_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycontact',
            name='last_message_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
